### PR TITLE
Clean up potentially-sensitive data based on feedback.

### PR DESCRIPTION
**Pull request by JinlianWang**
@AliSoftware I was asked to remove couple potentially sensitive data per corporate reviews (legal and info security departments). They are pure data without changing any code logic. Sorry for the trouble. By the way, I just sent an email asking for your feedback on the recording tool I created. If you can give me some feedback, that would be awesome. Thanks!

### CODE REVIEW

**Comment by AliSoftware** [comment]
No problem.

Actually, just realized I indeed missed to normalize the copyright info in the headers of your source files.

As `OHHTTPStubs` is under the MIT Licence, would you be ok to update the comments on top of your `.h/.m` files so that it matches [this](https://github.com/AliSoftware/OHHTTPStubs/blob/master/OHHTTPStubs/Sources/OHHTTPStubs.h#L1-L23), simply replacing my name with yours and the year with 2015?

Thx

**Comment by JinlianWang** [comment]
I would love to update the file with MIT license. Capital One especially the department I am working for is pushing for open source culture and unfortunately the authorship is one of the main KPIs. I would have to check to see what we can do. Actually the other day some leadership asked why I am not showing as one of the contributors:-(

**Comment by AliSoftware** [comment]
> I would have to check to see what we can do. Actually the other day some leadership asked why I am not showing as one of the contributors

I actually can't keep your code in my repo if it's not under MIT as it would violate the license I release my code under, so please do.

You've been listed as a contributor / credited in the CHANGELOG already.
I'd also be glad if you credit yourself at the bottom of the README in the contributors section.

**Comment by JinlianWang** [comment]
Just go ahead and update it. Going through the internal open source guidelines, it seems to be listed as one of acceptable samples. The company is pushing effort over open source and sponsoring events like http://www.iosdevcampdc.com. Would you be interested coming in as a speaker to share your experience if similar event occurs?

**Comment by AliSoftware** [comment]
I've merged everything to master, and added credits in README, so it should be good now 😃

> The company is pushing effort over open source and sponsoring events like http://www.iosdevcampdc.com. Would you be interested coming in as a speaker to share your experience if similar event occurs?

Sure! Never went to DC (or even the US) yet, but could be interesting to be a speaker at one of those events :+1:

**Comment by JinlianWang** [comment]
@AliSoftware Thanks a bunch for the flexibility!!! Will check with you when such events occur. 

By the way, since this is merged to master, I will close this pull request.

**Pull request closed without merging**
