### PR TITLE
Updated ios min deployment target to 11 for xcode 14.3 support.

### PR DESCRIPTION
**Pull request by adamsousa**
### Checklist

- [x] I've checked that all new and existing tests pass
- [x] I've updated the documentation if necessary
- [x] I've added an entry in the CHANGELOG to credit myself

### Description

Updated iOS deployment target to iOS 11, minimum supported in Xcode 14.3

### Motivation and Context

Allows framework to be built using xcode 14.3

### CODE REVIEW

**Comment by kishorepran** [comment]
@adamsousa : there are more places this needs to be updated. i.e. podspec, podfile etc.

**Review by MagFer — APPROVED** [review]
Can we help this good man (@adamsousa) to merge the PR? 

Using his commit from the forked branch has been the only way I've found to recompile the OHHTTPStubs with Carthage in Xcode 14.3.1.

image

Here you can see the error (left) and success (right) terminal logs.

image

This was the error log from Carthage.

255984453-b4b797fd-eeb1-4dd4-b338-36681e626a76

Regarding People using CocaPods, perhaps you can suggest which pod-related file lines must be changed or send a PR to https://github.com/adamsousa/OHHTTPStubs/tree/xcode-14.3.

**Comment by Liquidsoul** [comment]
Thank you all for your work and sorry I could not look into this sooner.

So we're stuck here because I do not have the rights to bypass the required CI step that does not seem to run.

I've gathered all the bumping changes in [this branch](https://github.com/AliSoftware/OHHTTPStubs/tree/bump/deployment-targets) and I will try to reach @AliSoftware to see if I can get the administrator rights on this. Let's hope that this is resolved soon 🤞

**Comment by AliSoftware** [comment]
Sorry for the huge delay on this.

@Liquidsoul It seems GitHub doesn't have an option to give administrator access to a repo if it's a personal repo and not in a [Team Organization](https://github.com/organizations/plan) 😞

**Comment by adamsousa** [comment]
@AliSoftware I updated my PR with podfile and .podspec targeting iOS 11. Also updated the example projects.

**Comment by kishorepran** [comment]
@AliSoftware : you can give me collaborator access. in that way I can help raise a pr that migrates from CI to GitHub actions. I have done this for many projects. Thanks.
https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-your-project/managing-access-to-your-projects

**Comment by kishorepran** [comment]
> @AliSoftware I updated my PR with podfile and .podspec targeting iOS 11. Also updated the example projects.

Package.Swift update missing. need to update that as well.

**Review by kishorepran — CHANGES_REQUESTED** [review]
Need to cover the case for package.swift as well.

**Comment by adamsousa** [comment]
Added

**Review by kishorepran — APPROVED** [review]
good to go now.

**Comment by kikeenrique** [comment]
I miss a bump in tvOS deployment version as its minimal version is tvOS 11 in Xcode 14.X 
At least for SPM (check for reference my PR https://github.com/AliSoftware/OHHTTPStubs/pull/352)

**Comment by arjankowski** [comment]
Hi @AliSoftware @Liquidsoul, is there any chance of merging this PR?

**Review by Liquidsoul — APPROVED** [review]

**Pull request merged**
