### PR TITLE
Renamed `Example` folder to `Sample` to fix `Carthage` dependency manage...

### PR DESCRIPTION
**Pull request by YasKuraishi**
Fixed: https://github.com/AliSoftware/OHHTTPStubs/issues/97

### CODE REVIEW

**Comment by AliSoftware** [comment]
This will probably break `pod try` support.

**Comment by angrauel** [comment]
Please don't drop Carthage support. A lot of people use it instead of cocoapods

**Comment by Goles** [comment]
I must +1 the petition of not dropping Carthage support :+1:

**Comment by AliSoftware** [comment]
Be reassured, I won't drop it… but I won't corrupt/amend my project just to fix/workaround Carthage bugs either (and #97 — which this PR was a _workaround_ for — is indeed a Carthage issue, not mine).

**Comment by rogernolan** [comment]
:+1: for that view. I think Carthage should add the flexibility to specify a target.

**Pull request closed without merging**
