### PR TITLE
Add missing import to support building with Bazel

### PR DESCRIPTION
**Pull request by thii**
### Checklist

- [x] I've checked that all new and existing tests pass
- [x] I've updated the documentation if necessary
- [x] I've added an entry in the CHANGELOG to credit myself

### Description
Add missing import to support building with Bazel, since it doesn't import underlying system modules by default.

### CODE REVIEW

**Comment by jeffctown** [comment]
@thii Hey!  Thanks so much for putting this up.  If you edit the changelog for this PR, I don't see a problem merging it in.  

Do you by any chance have the time to add a BUILD file so other Bazel users can integrate with this repo easily?

**Comment by thii** [comment]
@jeffctown Unfortunately we can't open source the BUILD file for it now.

This only adds a missing import (which implicitly gets imported if building with Xcode) so I think it's OK to skip the changelog to keep it clean.

**Comment by thii** [comment]
I've updated the changelog and added a BUILD file for it.

**Review by jeffctown — APPROVED** [review]

**Comment by thii** [comment]
Looks like the BUILD file was moved to a different directory, probably unintentionally?

**Comment by jeffctown** [comment]
@thii good catch.  I'm not sure how that happened, but I'll clean it up this weekend and do a v10 release.

**Pull request merged**
