### PR TITLE
Adding tvos support for 'Swift' subspec

### PR DESCRIPTION
**Pull request by pantuspavel**

### CODE REVIEW

**Comment by AliSoftware** [comment]
Ah! Isn't it inherited from the parent specification?

If so we'll probably need to re-specify it for `watchOS` too then.

**Comment by AliSoftware** [comment]
Could you add the `watchOS` platform to the `Swift` subspec too, and add a `## Master` entry in the `CHANGELOG` for that change? Thanks

**Comment by pantuspavel** [comment]
Hi, thanks for merging. Will definitely add watchOS platform when have a minute.

**Comment by AliSoftware** [comment]
Don't bother: I finally did it myself along with the CHANGELOG :wink:

**Comment by AliSoftware** [comment]
`4.5.1` released to CocoaPods! Thx again for the PR

**Comment by pantuspavel** [comment]
That's fast! Thank you! Time to update my Podfile ;)

**Pull request merged**
