### PR TITLE
Enables application extension API only

### PR DESCRIPTION
**Pull request by lightsprint09**
### Checklist

- [x] I've checked that all new and existing tests pass
- [x] I've updated the documentation if necessary
- [x] I've added an entry in the CHANGELOG to credit myself

### Description

Adds support for using OHHTPStubs in application extension.  OHHTPStubs does not use any API which is restricted inside extension, so enabling support is just ticking 3 boxes (iOS, macOS, tvOS). 

### Motivation and Context

Linking OHHTPStubs to an application extension works find but creates a warning. This change targets a warning free project.

### CODE REVIEW

**Comment by lightsprint09** [comment]
Thanks for the quick reply. 
Added a changlog and waiting for your comments now.

**Comment by marcussc** [comment]
@lightsprint09 @AliSoftware is there anything I can help with to get this merged?

**Comment by AliSoftware** [comment]
Sorry for not being super responsive, haven't had a lot of time to work on my many OSS lately, and I don't have a Mac at home anymore (keyboard repair in progress) to test this PR unfortunately.

@marcussc You could try to integrate the fork in a project (If you're integrating it using CocoaPods, just use `pod 'OHHTTPStubs', :git => 'https://github.com/lightsprint09/OHHTTPStubs', :branch => 'extension-support'` in your `Podfile`), do a clean build, and confirm it solves the problem. If so, I'll probably merge it right away.

**Comment by marcussc** [comment]
@AliSoftware Just integrated the Fork in inside my Project via Carthage. After a clean build the warning is gone. Looks good for me 👍

**Comment by AliSoftware** [comment]
Cool, thx 👍 

I have a few other PRs left on which I've been late on reviewing and merging, will try to catch up on them all this week so I can release of a new version properly ASAP 😅

**Pull request merged**
